### ISSUE TITLE
Post: Qual sua legenda?

### ISSUE THREAD

**Issue by augustoqm** [analytics-ufcg/vereadorescg-site#30]
Post similar ao Qual seu partido? mas dessa vez comparando partidos com o passar dos anos.
Os partidos possuem ideologias de certa forma bem definidas nacionalmente. Mas em Campina Grande mesmo essas definições não se sustentam. As coligações unem partidos com ideologias bem distintos.
- [ ] Usar os dados da localização de cada partido no espectro político ([wikipedia](https://pt.wikipedia.org/wiki/Lista_de_partidos_pol%C3%ADticos_no_Brasil)) para expor como uma legenda reúne partidos de diferentes partes (muitas vezes opostas) do espectro político.

Query pra começar:
_select \* from consulta_legendas where nome_ue = 'CAMPINA GRANDE' and ano_eleicao in (2008, 2012, 2016) and descricao_cargo = 'VEREADOR';_

**Comment by nazareno** [comment]
Substituí a wikipedia como fonte pelo Observatório das elites :)
http://observatory-elites.org/
