### ISSUE TITLE
Página Todos Juntos (e no tempo) - Não mostra gráfico

### ISSUE THREAD

**Issue by augustoqm** [analytics-ufcg/vereadorescg-site#8]
[https://nazareno.github.io/vereadorescg-site//2016/09/ao-longo-do-tempo.html](https://nazareno.github.io/vereadorescg-site//2016/09/ao-longo-do-tempo.html)

**Comment by nazareno** [comment]
É um problema no HTTPS no LSD. Estamos tentando resolver

**Comment by nazareno** [comment]
Nossa api agora é https e a URL mudou: 

https://wwws.cloud.lsd.ufcg.edu.br:44142/ementas/contagem?count_by=tipo
